spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    ecsdemoFrontend:
      repoURL: https://github.com/seb-demo/eks-blueprints-workloads
      #repoURL: https://github.com/aws-containers/ecsdemo-frontend.git      
      targetRevision: main
      #path: kubernetes/helm/ecsdemo-frontend
      path: teams/ecsdemo-frontend/dev
    ecsdemoNodejs:
      repoURL: https://github.com/aws-containers/ecsdemo-nodejs.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-nodejs
    ecsdemoCrystal:
      repoURL: https://github.com/aws-containers/ecsdemo-crystal.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-crystal