spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/seb-demo/eks-blueprints-workloads
    targetRevision: main
  ingress:
    host: prod.example.com